export const predefTags = [
  "Appetizers",
  "Main Course",
  "Desserts",
  "Vegetarian",
  "Vegan",
  "Gluten-Free",
  "Dairy-Free",
  "Quick & Easy",
  "Healthy",
  "Low-Carb",
  "Pasta",
  "Salads",
  "Soups",
  "Grilled",
  "Breakfast",
  "Snacks",
  "Seafood",
  "Chicken",
  "Baking",
  "Comfort Food",
]